### ISSUE TITLE
Bug report: diff formating of string will check the text including text generated by gop format(like style text and comment), and it will appear incorrectly.

### ISSUE THREAD

**Issue by skyf0cker** [ysmood/got#10]
You can try this:
```golang
package main

import (
	"testing"

	"github.com/ysmood/got"
)

func TestTestFunc(t *testing.T) {
	// string length greater than 16
	got.T(t).Eq("3", "abcdedasdasassa1")
}

```

what i got:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/32331521/165304993-f0e626a8-4e40-4e66-97de-4b22ffe78acd.png">

**Comment by skyf0cker** [comment]
it also looks weird  that using result of gop format to do the diff work.
https://github.com/ysmood/got/blob/2338a2006a4c77f126e418061f5628017351b690/assertions_error.go#L122
Hope to get your reply if there are anything wrong.
@ysmood

**Comment by skyf0cker** [comment]
Thanks for your fix. I have tried the lastest version. But i don't if this result is expected. 
The comment like "/* len=16 */" is not the native content that user got. So i don't think it is appropriate to show these in diff result.

<img width="755" alt="image" src="https://user-images.githubusercontent.com/32331521/165447420-d8f00a91-1fe6-4d57-8894-5d9b174b2ebe.png">

```golang
module gotdemo

go 1.16

require github.com/ysmood/got v0.25.2-0.20220427052241-86a0cab4c193

```

**Comment by ysmood** [comment]
I think it's not an issue because their string length is different.

**Comment by ysmood** [comment]
We can open another issue to discuss what should we do, I think it's out of the scope of this issue.

**Comment by skyf0cker** [comment]
It has no matter with length. ppl who use this tool to do test jobs just want to get the diff between what they expect and what they actual got. You can show comments but in "add word" style is wired and confusing.



---Original---
From: "Yad ***@***.***&gt;
Date: Wed, Apr 27, 2022 13:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ysmood/got] Bug report: diff formating of string will check the text including text generated by gop format(like style text and comment), and it will appear incorrectly. (Issue #10)




 
We can open another issue to discuss what should we do, I think it's out of the scope of this issue.

**Comment by ysmood** [comment]
But the code below is valid golang code:

```go
"test"/* len=4 */
```

**Comment by ysmood** [comment]
If you want to disable this length output you can increase the config like this:

```go
gop.LongBytesLen = 100000000
```
