### ISSUE TITLE
我已经是第四次找不到gop这个库了

### ISSUE THREAD

**Issue by pnck** [ysmood/got#20]
并且是第四次在 v2ex 上搜索 `gop` 才找回来的

**我收藏了。一开始就。**

请问能否把 `gop` utils 独立出去？ 或者至少在首页的 README 上给一个相关的 example, 否则实在是很难看到

**Comment by ysmood** [comment]
因为只有测试的时候会用到 gop，所以就放到 got 里了，确实可以独立出去，它没有什么依赖

**Comment by ysmood** [comment]
你在非测试代码里也会用到 gop 吗？

**Comment by pnck** [comment]
> 你在非测试代码里也会用到 gop 吗？

不会。其实一般都是 debug 的时候才会需要个比较好的 pretty print，单元测试写好存档时通常会精简成只返回结果的形式， pretty print 反而会 flood 控制台输出。


另外既然作者还在，想顺便问问有没有能与标准库 logger 结合的方法？ 如果可以的话就能当成 error dump 来用了，现在只能在控制台中找字段还是比较局限的，好看大于实用意义
