### ISSUE TITLE
Improve the words sequence for lines

### ISSUE THREAD

**Issue by ysmood** [ysmood/got#8]
We should also consider the non-English words, such as for sentences like `find a place to eat 热干面` we should split it into:

- find
- a
- place
- to
- eat
- 热
- 干
- 面

The current way we do it is not performant:

https://github.com/ysmood/got/blob/2338a2006a4c77f126e418061f5628017351b690/lib/diff/sequence.go#L33-L36

**Comment by MamaShip** [comment]
Hi~ I'm [twistedmeadows](https://v2ex.com/member/twistedmeadows) from v2ex.

I find this function currently not working as you described.

------------------

with input `"find a place to eat"`, it returns a `[]Comparable` like this:

```
String: f  Hash: f
String: i  Hash: i
String: n  Hash: n
String: d  Hash: d
String:    Hash:
String: a  Hash: a
String:    Hash:
String: p  Hash: p
String: l  Hash: l
String: a  Hash: a
String: c  Hash: c
String: e  Hash: e
String:    Hash:
String: t  Hash: t
String: o  Hash: o
String:    Hash:
String: e  Hash: e
String: a  Hash: a
String: t  Hash: t
```

Is this what you want in the first place？

**Comment by MamaShip** [comment]
guess this is the solution for non-English words

https://github.com/MamaShip/got/blob/9bb43b1f84057c534cc68061bfb32c940d768365/lib/diff/sequence.go#L36-L38

**Comment by ysmood** [comment]
You can write some tests for it, I think yours should fail.

**Comment by MamaShip** [comment]
> You can write some tests for it, I think yours should fail.

yeah actually I've tested it with

```
func TestNewString(t *testing.T) {
	out := diff.NewString("find a place to eat 热干面")
	fmt.Println(len(out))
	for _, c := range out {
		fmt.Println("String:",c," Hash:",c.Hash())
	}
}
```

and the result is 

```
=== RUN   TestNewString
23
String: f  Hash: f
String: i  Hash: i
String: n  Hash: n
String: d  Hash: d
String:    Hash:
String: a  Hash: a
String:    Hash:
String: p  Hash: p
String: l  Hash: l
String: a  Hash: a
String: c  Hash: c
String: e  Hash: e
String:    Hash:
String: t  Hash: t
String: o  Hash: o
String:    Hash:
String: e  Hash: e
String: a  Hash: a
String: t  Hash: t
String:    Hash:
String: 热  Hash: 热
String: 干  Hash: 干
String: 面  Hash: 面
--- PASS: TestNewString (0.00s)
PASS
```

Meanwhile, before I make changes, the test fails with panic

```
=== RUN   TestNewString
29
String: f  Hash: f
String: i  Hash: i
String: n  Hash: n
String: d  Hash: d
String:    Hash:
String: a  Hash: a
String:    Hash:
String: p  Hash: p
String: l  Hash: l
String: a  Hash: a
String: c  Hash: c
String: e  Hash: e
String:    Hash:
String: t  Hash: t
String: o  Hash: o
String:    Hash:
String: e  Hash: e
String: a  Hash: a
String: t  Hash: t
String:    Hash:
String: 热  Hash: 热
--- FAIL: TestNewString (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5a2d2f]
```

That's why I asked about the purpose of this function.

**Comment by MamaShip** [comment]
> > I find this function currently not working as you described.
> 
> Yes, that's why we created this issue.
> 
> You can write some tests for it, I think yours doesn't work for English words.

OK, well received. 

So as you described, what you want is:

- split the string with space（or any kind of blank character？）
- ignore those space
- keep the integrity of English words
- split Chinese words into individual characters( what about other languages? do the same? )

**Comment by ysmood** [comment]
> or any kind of blank character?

Yes, here is some code you can reuse:

https://github.com/ysmood/got/blob/85320fbd604589c5bbffd5b6aaed9e3b5e7eeaec/lib/gop/style.go#L90

> what about other languages? do the same?

Yes, such as Japanese, Korean, etc. Usually, it requires AI to split symbol-based languages into words, we don't want to make it so completed, we can optimize them later.

Also, the name `Char` should be changed into something like `Word`:

```go

// Word block
type Word string

// Hash interface
func (c Word) Hash() string {
	return string(c)
}

// String interface
func (c Word) String() string {
	return string(c)
}

// NewWords from string
func NewWords(s string) Comparables {
	// need to be implemented
}
```

**Comment by MamaShip** [comment]
@ysmood OK, that make sense to me.
`Char` confuses me a lot.

**Comment by MamaShip** [comment]
I‘ll do this later today, maybe you can assign it to me. 😃

**Comment by ysmood** [comment]
We also have to split long strings without space into words, such as split `abcdefghijklmopqrst` into

- `abcdefghij`
- `klmopqrst`

Usually, it's achieved with a max word length limit, such as 20.

Also we should consider all symbols like, `.`, `_`, `-`, `,`, etc as splitters, not just blank chars.

**Comment by MamaShip** [comment]
> Also, we should consider all symbols like, `.`, `_`, `-`, `,`, etc as splitters, not just blank chars.

Should I keep the splitters or not?

**Comment by ysmood** [comment]
> Should I keep the splitters or not?

Yes, since it will be used for diff output.
